### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by clement-berard** [jlobos/instagram-web-api#102]
Hello everybody ! First, a big thank you for the development of this script ! :heart: 

But I try to simply login: 

```
const Instagram = require('instagram-web-api')

const client = new Instagram({ username: 'my_username', password: 'my_password' })
    ; (async () => {
        await client.login()
    })()
```
I try with a personal account of instagram.

**but I have this error:** 

```
node:5320) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at request.then.res (/home/********/node_modules/instagram-web-api/lib/index.js:56:82)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
const { value } = await this.request('/', { resolveWithFullResponse: true })
      .then(res => res.headers['set-cookie'].map(Cookie.parse))
      .then(res => res.find(cookie => cookie.key === 'csrftoken'))
      .then(res => res.toJSON())
```

The error comes from line 55, on the "set-cookie map". 

any idea? :bulb:  Thank you all! :smiley:

**Comment by MonsieurBibo** [comment]
Are you still having this problem ?
