### ISSUE TITLE
Handle network errors

### ISSUE THREAD

**Issue by tarkh** [jlobos/instagram-web-api#105]
Hello!
Thanx for nice soft, everything works cool, however I cat't figure how to properly handle connection errors in proper way? I.e. this is one of common cases, when error happens and after that API stops working and need to be restarted:
```JavaScript
(node:67811) UnhandledPromiseRejectionWarning: RequestError: Error: read ECONNRESET
    at new RequestError (./node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (./node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (./node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (./node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (./node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
(node:67811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 65)
(node:67811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Doing `try { ... } catch(e) { ... }` does not solve the problem, maybe we need some extra methods built in instagram-web-api module?
Thanx!

**Comment by ailinykh** [comment]
Probably you should use `catch` method on Promise
```javascript
await client.getProfile()
    .catch(e => console.error(e))
```
