### ISSUE TITLE
client.uploadPhoto not works

### ISSUE THREAD

**Issue by 0x77dev** [jlobos/instagram-web-api#114]
const FileCookieStore = require('tough-cookie-filestore2')
const Instagram = require('instagram-web-api')
const { username, password, accounts } = process.env

const cookieStore = new FileCookieStore('./cookies.json')
const client = new Instagram({ username, password, cookieStore });

const uploadPhoto = async (photo) => {
    const { media } = await client.uploadPhoto(photo)
    return media;
}

(async () => {
    await client.login()
    await client.uploadPhoto("https://habrastorage.org/webt/or/77/t4/or77t4go_qqok-v8qnenx5rxcjy.png")
   // Or Even Like This
  // ./or77t4go_qqok-v8qnenx5rxcjy.png

})()

```console
(node:31679) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.open (fs.js:423:10)
    at _openReadFs (internal/fs/streams.js:158:15)
    at new ReadStream (internal/fs/streams.js:135:5)
    at Object.createReadStream (fs.js:1835:10)
    at Instagram._uploadPhoto (/Users/0x77/0x77.memes/node_modules/instagram-web-api/lib/index.js:330:51)
    at Instagram.uploadPhoto (/Users/0x77/0x77.memes/node_modules/instagram-web-api/lib/index.js:345:17)
    at /Users/0x77/0x77.memes/index.js:15:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:31679) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:31679) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 ~/0x77.memes  wget ^C
 ~/0x77.memes  curl -O https://habrastorage.org/webt/or/77/t4/or77t4go_qqok-v8qnenx5rxcjy.png                                                                                  1356ms < четверг,  9 апреля 2020 г. 22:43:55
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0   1169      0 --:--:-- --:--:-- --:--:--  1169
 ~/0x77.memes  node index.js                                                                                                                                                    158ms < четверг,  9 апреля 2020 г. 22:43:56
(node:31748) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.open (fs.js:423:10)
    at _openReadFs (internal/fs/streams.js:158:15)
    at new ReadStream (internal/fs/streams.js:135:5)
    at Object.createReadStream (fs.js:1835:10)
    at Instagram._uploadPhoto (/Users/0x77/0x77.memes/node_modules/instagram-web-api/lib/index.js:330:51)
    at Instagram.uploadPhoto (/Users/0x77/0x77.memes/node_modules/instagram-web-api/lib/index.js:345:17)
    at /Users/0x77/0x77.memes/index.js:15:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:31748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:31748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by codexJoin** [comment]
Wrong Code!

just  do:

```js
    await client.uploadPhoto({photo: 'url image or path'}).catch((error) => {
    	console.log(`An error occurred on uploading photo: ${error}`);
    }).then((responseUpload) => {
    	console.loog(responseUpload)
    })

**Comment by 0x77dev** [comment]
It helped, thanks!

**Comment by erhancan256** [comment]
> Wrong Code!
> 
> just do:
> 
> ```js
>     await client.uploadPhoto({photo: 'url image or path'}).catch((error) => {
>     	console.log(`An error occurred on uploading photo: ${error}`);
>     }).then((responseUpload) => {
>     	console.log(responseUpload)
>     })
> ```

thank you codex
