### ISSUE TITLE
getProfile returned UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by lucasabreuo** [jlobos/instagram-web-api#154]
I used an example code and got UnhandledPromiseRejectionWarning.

Code:
```
const client = new Instagram({ username, password });

;(async () => {
  await client.login()
  const profile = await client.getProfile()
 
  console.log(profile)
})()

```
Error:
`(node:6188) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - {"message":"checkpoint_required","checkpoint_url":"/challenge/533517877/UL7dRZzIvc/","lock":false,"status":"fail"}
    at new StatusCodeError (C:\api\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\api\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\api\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\api\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (C:\api\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (C:\api\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:6188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

How to fix?

**Comment by danilosetra** [comment]
It’s asking for a checkpoint challenge. Take a look on this log you sent and the docs about getChallenge #getchallengeparams

**Comment by lucasabreuo** [comment]
Hi @danilosetra, thanks for answer.

How do I get this checkpoint? In the docs getChallenge it is written like this:

`await client.getChallenge({ challengeUrl: '/challenge/1284161654/a1B2c3d4E6/' })`

I realized that the return of this function is HTML, but I don't know what to do with it.

Best regards,

**Comment by eoboite** [comment]
Wrap your the code with a try/catch block for better error handling
