### ISSUE TITLE
Error code 560? What is that?

### ISSUE THREAD

**Issue by ronaldho** [jlobos/instagram-web-api#183]
Hello,

When posting comments, I get a code 560 from instagram, but I cannot find anyone talking about this, so I am wondering if anyone happened to also hit the same issue?

Here is a brief snippet of the stack trace:
```
StatusCodeError: 560 - undefined
    at new StatusCodeError (/home/r/instagram-queued/backend/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/r/instagram-queued/backend/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/r/instagram-queued/backend/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/r/instagram-queued/backend/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/r/instagram-queued/backend/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/r/instagram-queued/backend/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
  name: 'StatusCodeError',
  statusCode: 560,
  message: '560 - undefined',
  error: undefined,
  options:
   { baseUrl: 'https://www.instagram.com',
     uri: '/web/comments/2393878018101540707_145704821/add/',
     headers:
      { 'User-Agent':
         'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:21.0) Gecko/20100101 Firefox/21.0',
        'Accept-Language': 'en-US',
        'X-Instagram-AJAX': 1,
        'X-CSRFToken': 'EJbdpopO0S2fY3zRaw1PAztqEZUjvj5u',
        'X-Requested-With': 'XMLHttpRequest',
        Referer: 'https://www.instagram.com' },
     jar: RequestJar { _jar: [CookieJar] },
     json: true,
     form: { comment_text: '@blah' },
     method: 'POST',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
```

**Comment by MonsieurBibo** [comment]
I believe 5xx errors come from server's issues. Are you still having this problem ?

**Comment by ronaldho** [comment]
I didn't end up diagnosing it properly, but anecdotally, it seemed to be connected with a cool down on the account (for doing too many actions simultaneously)

I'll close this ticket for now, but if I have any updates, I'll reopen it 😃

**Comment by egoistBikash** [comment]
this totally server issue not client side issue. not even the behalf of instagram too

**Comment by SwallowData** [comment]
> this totally server issue not client side issue. not even the behalf of instagram too

Is it possible that my crawler will be recognized by the server?
