### ISSUE TITLE
rejecting a promise which was not handled with .catch()

### ISSUE THREAD

**Issue by bsde1234** [jlobos/instagram-web-api#185]
When I run  
```
const Instagram = require('instagram-web-api')
const username = 'keralap';
const password = 'aasdasd';
const client = new Instagram({ username:username, password:password })
;(async () => {
  await client.login()
  for(var i=0; i<62804; i++){
  const photo =
    '/home/justine/web/telegrammq/instaq/py/'+i+'.jpg'
  const { media } = await client.uploadPhoto({ photo: photo, caption: 'Kerala PSC', post: 'feed' })
  }
})()
```

I get after some uploads  

```
(node:5335) UnhandledPromiseRejectionWarning: StatusCodeError: 429 - {"message":"Please wait a few minutes before you try again.","status":"fail"}
    at new StatusCodeError (/home/justine/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/justine/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/justine/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/justine/node_modules/request/request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (/home/justine/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (/home/justine/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
(node:5335) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5335) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Did I make any mistake in code or is there an upload limit?

**Comment by codexJoin** [comment]
Instagram blocks your request because it understands it as spam, so you have to wait to send new photos, note, you created a loop, with more than 6000 uploads, that's why Instagram blocks it, don't make uploads that big with such a short interval .
