### ISSUE TITLE
Possible change of instagram api (client.getMediaFeedByHashtag({ hashtag }))

### ISSUE THREAD

**Issue by MGreif** [jlobos/instagram-web-api#186]
Requested page by getMediaFeedByHashtag not found 

`  const res = client.getMediaFeedByHashtag({hashtag: 'test'})`

Throws:

`
(node:474) UnhandledPromiseRejectionWarning: StatusCodeError: 501 - undefined
    at new StatusCodeError (/home/mika/Desktop/nodejs/instagramTests/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/mika/Desktop/nodejs/instagramTests/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/mika/Desktop/nodejs/instagramTests/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/mika/Desktop/nodejs/instagramTests/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/mika/Desktop/nodejs/instagramTests/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/mika/Desktop/nodejs/instagramTests/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
(node:474) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:474) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by hype08** [comment]
actually if you open up tags and enter any in the browser, seems like it's down
https://www.reddit.com/r/Instagram/comments/isvpu9/explore_page_not_working_on_browser/

**Comment by MGreif** [comment]
> actually if you open up tags and enter any in the browser, seems like it's down
> https://www.reddit.com/r/Instagram/comments/isvpu9/explore_page_not_working_on_browser/

Its up again. All works perfectly fine :)
