### ISSUE TITLE
Error 400 - spam:true

### ISSUE THREAD

**Issue by jublebi** [jlobos/instagram-web-api#216]
Hey guys I wrote a little script which unfollows a person every 70 to 100 Seconds. It did very well also when I have unfollowed 500 people over a few hours. Now I get this error when I try to start the script again. I probably have overused it, at least what I can see:

(node:3332) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - {"message":"feedback_required","spam":true,"feedback_title":"Try Again Later","feedback_m
st.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (J:\Projekte\instabot\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
(node:3332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Interesting is that when I start another script - to get my followers and followings - which uses the same Instagram Account no problems occur. So can anyone please explain to me what exactly went wrong and even more important how I can fix this.

P.S. I hope this post is okay :)

Edit: When I use Instagram with the same Account on my Mobile or in the browser unfollowing is still able

**Comment by MonsieurBibo** [comment]
Instagram has some internal tools that detect spam or automated actions. If they detect them, they can temporarily block your actions.

 The ban can be limited to a device or even a function and this explains your case. Rates depend on each account. 

I don't know of any solutions except to have a less automated behavior. Nobody IRL unfollows 500 peoples over a few hours ;)

**Comment by jublebi** [comment]
Ok and how long does it take to I unfollow again?

**Comment by MonsieurBibo** [comment]
Unfortunately I don't have any information about it
