### ISSUE TITLE
StatusCodeError: 403 - "{\"message\":\"login_required\",\"status\":\"fail\"}"

### ISSUE THREAD

**Issue by aikozim** [jlobos/instagram-web-api#217]
Hey Everyone! I am trying to get Basic uploading to Work but I can not even get my Account logged in succesfully. It is always giving me this Error:
```
(node:104828) UnhandledPromiseRejectionWarning: StatusCodeError: 403 - "{\"message\":\"login_required\",\"status\":\"fail\"}"
    at new StatusCodeError (C:\Users\aikoz\Desktop\Coding\Websites\Instagram-Bot\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\aikoz\Desktop\Coding\Websites\Instagram-Bot\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\aikoz\Desktop\Coding\Websites\Instagram-Bot\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\aikoz\Desktop\Coding\Websites\Instagram-Bot\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\aikoz\Desktop\Coding\Websites\Instagram-Bot\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\aikoz\Desktop\Coding\Websites\Instagram-Bot\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:104828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see 
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:104828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The Code I am currently using:
```
const Instagram = require('instagram-web-api');
const config = require("dotenv").config();

const password = process.env.IG_PASSWORD;
const username = process.env.IG_USERNAME;

const client = new Instagram({ username, password }, { language: 'de:DE' })
const photo = 'https://img1.gbpicsonline.com/gb/17/121.png'

postImage(photo, "hey!")

function postImage(photo, caption) {
    client.login()
      .then(async () => {
        await client.uploadPhoto({ photo, caption: caption, post: 'feed' });
      })
  }
```

**Comment by aikozim** [comment]
I got it.

**Comment by sujalgoel** [comment]
how you solved this issue? I am having the same error.

**Comment by MevlanaErtugrulAcikgoz** [comment]
Hi @DerSchmaik . How did you solve the problem? Can you help?

**Comment by aikozim** [comment]
I think back then ist was just a typo in my .env file. But I' am not sure anymore. Maybe you need some more code login first. (Lite it says in the error)
