### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by kars0nn** [jlobos/instagram-web-api#240]
Just started getting this issue last night, no clue why. Any help would be awesome

(node:13272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
<node_internals>/internal/process/warning.js:43
(node:13272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
<node_internals>/internal/process/warning.js:43
(node:13272) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at c:\Users\User\Documents\Spotify-insta\node_modules\instagram-web-api\lib\index.js:57:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Instagram.login (c:\Users\User\Documents\Spotify-insta\node_modules\instagram-web-api\lib\index.js:54:5)
<node_internals>/internal/process/warning.js:43

**Comment by kars0nn** [comment]
nevermind, i just had to reset my cookies file
