### ISSUE TITLE
error while split html

### ISSUE THREAD

**Issue by kiranharapradipta-gh** [jlobos/instagram-web-api#309]
html => html.split('window._sharedData = ')[1].split(';</script>')[0]
                                                      ^

TypeError: Cannot read properties of undefined (reading 'split')
    at C:\Users\kiran\code\instagram-web-api\node_modules\instagram-web-api\lib\index.js:109:55
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Instagram.login (C:\Users\kiran\code\instagram-web-api\node_modules\instagram-web-api\lib\index.js:100:26)

Node.js v20.11.0

i just do it

client.login().then(_ => {
    console.log('Logged in!')
    client.getProfile().then(console.log)
})

**Comment by zailio** [comment]
Ig bulk account creater tool available, dm me for more info,

Custom proxy,
Temp mail,
Web api
Follow/unfollow 
Bio, profile icon change,

auto comment, like, unlike and more

**Comment by NurAlan** [comment]
same issue

/Projects/node_modules/instagram-web-api/lib/index.js:110
        html => html.split('window._sharedData = ')[1].split(';</script>')[0]
                                                      ^

TypeError: Cannot read properties of undefined (reading 'split')
    at /Projects/node_modules/instagram-web-api/lib/index.js:110:55
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by qNanna** [comment]
Same
