### ISSUE TITLE
client.logout returns 405

### ISSUE THREAD

**Issue by chunheisiu** [jlobos/instagram-web-api#71]
I encounter a `405 - undefined` error when calling `client.logout`:

```
{ StatusCodeError: 405 - undefined
    at new StatusCodeError (/Users/chunheisiu/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/chunheisiu/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/chunheisiu/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/chunheisiu/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/Users/chunheisiu/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/Users/chunheisiu/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
  name: 'StatusCodeError',
  statusCode: 405,
  message: '405 - undefined',
  error: undefined,
  options: { ... },
  response: { ... }
}
```

Am I calling the method wrong?

**Comment by AlexanderProd** [comment]
Same here.

**Comment by behi1ty** [comment]
Same here.
