### ISSUE TITLE
Problem in simple login

### ISSUE THREAD

**Issue by kimia000** [jlobos/instagram-web-api#80]
I try to simply log in as

```
const Instagram = require('instagram-web-api');
const client = new Instagram({ username: 'XX', password: 'YY' });

(async () => {
   await client.login();
   const profile = await client.getProfile();
})();
```

but it returns the error:

```
TypeError: Cannot read property 'map' of undefined
    at request.then.res (/home/kimia/node_modules/instagram-web-api/lib/index.js:55:46)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by franzsilva** [comment]
I would place the code inside a try catch. so you can catch any errors returned.

``` javascript 
const Instagram = require('instagram-web-api');
const client = new Instagram({ username: 'XX', password: 'YY' });

(async () => {
    try {
        await client.login();
        const profile = await client.getProfile();
        console.log("Profile:", profile);
    } catch (error) {
        console.log("Error:", error);
    }

})();
```

**Comment by TheRTK** [comment]
I have same problem!

Instagram does not send header "set-cookie". 

instagram-web-api/lib/index.js:55:46
`.then(res => res.headers['set-cookie'].map(Cookie.parse))`

**Comment by Aljal** [comment]
Same problem here can someone help us pls ?

**Comment by gutosanches** [comment]
Looks like the package is outdated in npm. I fixed that by installing the package using the master branch putting this in my package.json:
`"instagram-web-api": "https://github.com/jlobos/instagram-web-api.git"`

**Comment by MonsieurBibo** [comment]
Is it still relevant ? If not can you close this issue please ?

**Comment by ruskid** [comment]
still relevant
