### ISSUE TITLE
getAllCookies is not implemented 

### ISSUE THREAD

**Issue by lucasvieceli** [jlobos/instagram-web-api#96]
```Error: getAllCookies is not implemented (therefore jar cannot be serialized)
    at FileCookieStore.Store.getAllCookies (/var/www/lucas/instagram/node_modules/tough-cookie/lib/store.j                                                                                                                                   s:74:9)
    at CookieJar.serialize (/var/www/lucas/instagram/node_modules/request/node_modules/tough-cookie/lib/co                                                                                                                                   okie.js:1273:14)
    at CookieJar.serializeSync (/var/www/lucas/instagram/node_modules/request/node_modules/tough-cookie/li                                                                                                                                   b/cookie.js:1402:18)
    at CookieJar.toJSON (/var/www/lucas/instagram/node_modules/request/node_modules/tough-cookie/lib/cooki                                                                                                                                   e.js:1294:15)
    at JSON.stringify (<anonymous>)
    at Object.exports.log (/var/www/lucas/instagram/index.js:76:21)
    at Object.<anonymous> (/var/www/lucas/instagram/instagram.js:62:17)
    at Generator.throw (<anonymous>)
    at rejected (/var/www/lucas/instagram/instagram.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

some accounts this error happens

**Comment by welber91** [comment]
Same problem

**Comment by adahox** [comment]
Same problem.
